// AlphaLatitude Inc. © 2026
//
// Drift guard: openapi.json's per-tool response schemas must mirror the MCP tool
// `outputSchema`s (they are generated by scripts/codegen/gen-openapi.mts). If a
// tool's output shape changes without regenerating, or a copy is hand-edited,
// this fails -- run `npm run gen:openapi`. The mcp copy is checked strictly; the
// cross-repo optionsahoy_web mirror only when present (absent in some CI).

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { TOOLS } from '../functions/_lib/mcp-tools';

// tool name -> REST slug + PascalCase component prefix (mirrors gen-openapi.mts).
const MAP = [
  ['amt_iso_optimize', 'amt-iso', 'AmtIso'],
  ['nso_calculate', 'nso', 'Nso'],
  ['rsu_sell_vs_hold', 'rsu-sell-vs-hold', 'Rsu'],
  ['concentration_analyze', 'concentration', 'Concentration'],
  ['protective_put_price', 'protective-put', 'ProtectivePut'],
  ['qsbs_check', 'qsbs', 'Qsbs'],
  ['equity_funding_plan', 'equity-funding', 'EquityFunding'],
] as const;

const MCP_PATH = 'public/openapi.json';
const WEB_PATH = '../optionsahoy_web/web/public/openapi.json';
const spec = JSON.parse(readFileSync(MCP_PATH, 'utf8'));
const byName = new Map(TOOLS.map((t) => [t.name, t]));

describe('openapi.json per-tool response schemas track the tool outputSchemas', () => {
  it('MAP covers every tool (a new tool cannot silently escape the guard)', () => {
    expect(MAP.length).toBe(TOOLS.length);
    for (const t of TOOLS) {
      expect(MAP.some(([name]) => name === t.name)).toBe(true);
    }
  });

  for (const [name, slug, prefix] of MAP) {
    it(`${slug}: 200 -> ${prefix}Success -> ${prefix}Result === ${name} outputSchema`, () => {
      // endpoint 200 references the per-tool success envelope
      expect(spec.paths[`/api/v1/${slug}`].post.responses['200']).toEqual({
        $ref: `#/components/responses/${prefix}Success`,
      });
      // the envelope's `result` references the per-tool result schema
      const envelope = spec.components.responses[`${prefix}Success`].content['application/json'].schema;
      expect(envelope.properties.result).toEqual({ $ref: `#/components/schemas/${prefix}Result` });
      expect(envelope.properties.ok).toEqual({ type: 'boolean', const: true });
      // the result schema mirrors the tool's MCP outputSchema exactly
      expect(spec.components.schemas[`${prefix}Result`]).toEqual(byName.get(name)!.outputSchema);
    });
  }

  it('no endpoint still uses the generic bare-result CalculatorSuccess', () => {
    for (const [, slug] of MAP) {
      expect(spec.paths[`/api/v1/${slug}`].post.responses['200']).not.toEqual({
        $ref: '#/components/responses/CalculatorSuccess',
      });
    }
  });

  it('web mirror is byte-identical to the mcp spec when present', () => {
    if (!existsSync(WEB_PATH)) {
      expect(true).toBe(true); // skipped: sibling repo not checked out
      return;
    }
    expect(readFileSync(WEB_PATH, 'utf8')).toEqual(readFileSync(MCP_PATH, 'utf8'));
  });
});
