// AlphaLatitude Inc. © 2026
//
// Drift guard: openapi.json's per-tool response schemas must mirror the MCP tool
// `outputSchema`s (they are generated by scripts/codegen/gen-openapi.mts). If a
// tool's output shape changes without regenerating, or a copy is hand-edited,
// this fails -- run `npm run gen:openapi`. The mcp copy is checked strictly; the
// cross-repo optionsahoy_web mirror only when present (absent in some CI).

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import Ajv2020 from 'ajv/dist/2020.js';
import { TOOLS } from '../functions/_lib/mcp-tools';
import { buildOpenApi } from '../scripts/codegen/gen-openapi.mjs';

// tool name -> REST slug + PascalCase component prefix (mirrors gen-openapi.mts).
const MAP = [
  ['amt_iso_optimize', 'amt-iso', 'AmtIso'],
  ['nso_calculate', 'nso', 'Nso'],
  ['rsu_sell_vs_hold', 'rsu-sell-vs-hold', 'Rsu'],
  ['concentration_analyze', 'concentration', 'Concentration'],
  ['protective_put_price', 'protective-put', 'ProtectivePut'],
  ['qsbs_check', 'qsbs', 'Qsbs'],
  ['equity_funding_plan', 'equity-funding', 'EquityFunding'],
  ['rsu_lot_optimize', 'rsu-lot-order', 'RsuLotOptimize'],
] as const;

const MCP_PATH = 'public/openapi.json';
const WEB_PATH = '../optionsahoy_web/web/public/openapi.json';
const spec = JSON.parse(readFileSync(MCP_PATH, 'utf8'));
const byName = new Map(TOOLS.map((t) => [t.name, t]));

describe('openapi.json per-tool response schemas track the tool outputSchemas', () => {
  it('MAP covers every tool (a new tool cannot silently escape the guard)', () => {
    expect(MAP.length).toBe(TOOLS.length);
    for (const t of TOOLS) {
      expect(MAP.some(([name]) => name === t.name)).toBe(true);
    }
  });

  for (const [name, slug, prefix] of MAP) {
    it(`${slug}: 200 -> ${prefix}Success -> ${prefix}Result === ${name} outputSchema`, () => {
      // endpoint 200 references the per-tool success envelope
      expect(spec.paths[`/api/v1/${slug}`].post.responses['200']).toEqual({
        $ref: `#/components/responses/${prefix}Success`,
      });
      // the envelope's `result` references the per-tool result schema
      const envelope = spec.components.responses[`${prefix}Success`].content['application/json'].schema;
      expect(envelope.properties.result).toEqual({ $ref: `#/components/schemas/${prefix}Result` });
      expect(envelope.properties.ok).toEqual({ type: 'boolean', const: true });
      // the result schema mirrors the tool's MCP outputSchema exactly
      expect(spec.components.schemas[`${prefix}Result`]).toEqual(byName.get(name)!.outputSchema);
    });
  }

  it('no endpoint still uses the generic bare-result CalculatorSuccess', () => {
    for (const [, slug] of MAP) {
      expect(spec.paths[`/api/v1/${slug}`].post.responses['200']).not.toEqual({
        $ref: '#/components/responses/CalculatorSuccess',
      });
    }
  });

  it('web mirror is byte-identical to the mcp spec when present', () => {
    if (!existsSync(WEB_PATH)) {
      expect(true).toBe(true); // skipped: sibling repo not checked out
      return;
    }
    expect(readFileSync(WEB_PATH, 'utf8')).toEqual(readFileSync(MCP_PATH, 'utf8'));
  });
});

describe('openapi.json request/response examples are the real engine I/O', () => {
  const media = (s: any) => s.content['application/json'];
  // One validator for the whole block: register the spec's components once so
  // $refs resolve, then compile per tool. Re-adding the same $id on one instance
  // throws, so this must stay a single addSchema.
  const ajv = new Ajv2020({ strict: false, allErrors: true });
  ajv.addSchema({ $id: 'oa', components: spec.components });

  // Master drift guard: regenerating (schemas + examples, calc output frozen to
  // a fixed clock inside buildOpenApi) must reproduce the committed file exactly.
  // A changed calc output, a hand-edited example, or a stale schema all fail here
  // -- run `npm run gen:openapi`. Subsumes the checks below, which stay for
  // readable per-tool failure messages.
  it('regenerating reproduces the committed spec byte-for-byte (run gen:openapi if this fails)', () => {
    // Compare the exact bytes the generator writes (JSON.stringify drops
    // `undefined`-valued props, matching the on-disk file) -- the same check
    // as `npm run verify:openapi`.
    const regenerated = JSON.stringify(buildOpenApi(), null, 2) + '\n';
    expect(regenerated).toEqual(readFileSync(MCP_PATH, 'utf8'));
  });

  for (const [, slug, prefix] of MAP) {
    it(`${slug}: has a request example and a { ok:true, result } response example`, () => {
      const reqExample = media(spec.paths[`/api/v1/${slug}`].post.requestBody).example;
      expect(reqExample && typeof reqExample).toBe('object');

      const respExample = media(spec.components.responses[`${prefix}Success`]).example;
      expect(respExample.ok).toBe(true);
      expect(respExample.result && typeof respExample.result).toBe('object');
    });

    it(`${slug}: response example validates against the ${prefix}Result schema`, () => {
      // The example is literal calc output; if it fails its own schema, the
      // outputSchema misdescribes what the engine actually returns.
      const validate = ajv.compile({ $ref: `oa#/components/schemas/${prefix}Result` });
      const result = media(spec.components.responses[`${prefix}Success`]).example.result;
      expect(validate(result), JSON.stringify(validate.errors)).toBe(true);
    });
  }
});
