// AlphaLatitude Inc. © 2026
//
// ToolName is the one hand-maintained list of tool names in the repo (see
// functions/_lib/mcp-tools.ts). Everything else that needs a per-tool entry is
// keyed on it, so a new tool becomes a compile error at every lookup table
// rather than a grep exercise. These tests pin the parts the compiler cannot
// see: that the union matches TOOLS, and that the surfaces built from plain
// JSON / hand-written arrays stay in step.
//
// Background: adding the EIGHTH tool required hand-editing roughly twenty
// `Record<string, ...>` tables across poe.ts, sessions.ts, a2a.ts and the
// codegen scripts. One miss shipped (the web repo's MCPTryIt TOOL_ORDER), and a
// missing poe FRIENDLY entry would have put "undefined" into the bot's help
// text. The types now prevent that class; this file guards the seams.

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { TOOLS, TOOL_NAMES, isToolName, type ToolName } from '../functions/_lib/mcp-tools';
import { SKILLS } from '../functions/_lib/a2a';
import {
  PER_TOOL_FREE_TOOL,
  PER_TOOL_FREE_TOOL_BARE,
  PER_TOOL_RELATED,
  PER_TOOL_BETA_INVITES,
} from '../functions/_lib/sessions';

const NAMES: ToolName[] = TOOLS.map((t) => t.name);

describe('ToolName is the single source of tool names', () => {
  it('TOOL_NAMES is derived from TOOLS and cannot drift from it', () => {
    expect([...TOOL_NAMES].sort()).toEqual([...NAMES].sort());
  });

  it('every tool name in TOOLS is a valid ToolName', () => {
    // The union is hand-maintained; McpTool.name is typed to it, so a tool whose
    // name is absent from the union fails to compile. This asserts the runtime
    // guard agrees.
    for (const n of NAMES) expect(isToolName(n)).toBe(true);
  });

  it('isToolName rejects near-misses rather than trusting the caller', () => {
    expect(isToolName('rsu_lot_order')).toBe(false); // the SLUG, not the tool name
    expect(isToolName('rsu_lot_optimise')).toBe(false); // British spelling
    expect(isToolName('')).toBe(false);
    expect(isToolName('__proto__')).toBe(false);
  });

  it('no duplicate tool names', () => {
    expect(new Set(NAMES).size).toBe(NAMES.length);
  });
});

describe('per-tool surfaces cover every tool', () => {
  // These four are Record<ToolName, string>, so a missing key already fails to
  // compile. Kept as runtime assertions because they are the difference between
  // a tool advertising its follow-ups and silently advertising nothing.
  it.each([
    ['PER_TOOL_FREE_TOOL', PER_TOOL_FREE_TOOL],
    ['PER_TOOL_FREE_TOOL_BARE', PER_TOOL_FREE_TOOL_BARE],
    ['PER_TOOL_RELATED', PER_TOOL_RELATED],
    ['PER_TOOL_BETA_INVITES', PER_TOOL_BETA_INVITES],
  ])('%s has a non-empty entry for every tool', (_label, map) => {
    for (const n of NAMES) {
      expect((map as Record<string, string>)[n], `missing entry for ${n}`).toBeTruthy();
    }
  });

  it('a2a advertises exactly one skill per tool', () => {
    expect(SKILLS.map((s) => s.id).sort()).toEqual([...NAMES].sort());
  });

  // The published agent card is a committed JSON artifact regenerated by hand,
  // so nothing in the type system connects it to TOOLS.
  it('the committed agent card lists every tool', () => {
    const card = JSON.parse(readFileSync('public/.well-known/agent-card.json', 'utf8'));
    const ids = (card.skills ?? []).map((s: { id: string }) => s.id).sort();
    expect(ids).toEqual([...NAMES].sort());
  });
});
