// AlphaLatitude Inc. © 2026
//
// ChatGPT Apps SDK widget: the one path where our scenario link reaches the
// user VERBATIM.
//
// Why this exists. `content` and `structuredContent` are, per OpenAI's own
// reference, "surfaced to the model" - the assistant composes its reply FROM
// them, so a 400-char base64 scenario payload is regenerated by a language
// model and routinely mangled. Six observed ChatGPT runs of one question gave
// five different link treatments (omitted twice, whole once, src-only, twice
// stripped to the bare path). No instruction fixes that channel; it is lossy
// by construction.
//
// A widget is rendered by the CLIENT, not written by the model. An <a href>
// here arrives exactly as sent.
//
// ADDITIVE BY DESIGN. Everything else is untouched: content[0] stays the JSON
// result, content[1] stays the prose block carrying the same full URL, and
// clients that do not implement `_meta["openai/outputTemplate"]` (Claude,
// Cursor, npx/stdio, registries, plain SDK callers) see byte-identical
// responses to before. Per MCP spec, unknown `_meta` keys are ignored.

/** Widget template URI, referenced from each tool's `_meta`. */
export const SCENARIO_WIDGET_URI = 'ui://widget/optionsahoy-scenario.html';

/** Tool-descriptor `_meta` that opts ChatGPT into the widget. */
export const SCENARIO_WIDGET_META = {
  'openai/outputTemplate': SCENARIO_WIDGET_URI,
  'openai/toolInvocation/invoking': 'Running the numbers',
  'openai/toolInvocation/invoked': 'Calculation complete',
} as const;

// Self-contained: no external scripts, styles, fonts or images, so no
// `_meta.ui.csp` declaration is needed and the sandbox cannot block us.
//
// The component reads `window.openai.toolOutput` (our structuredContent) and
// renders next_steps.web_tool as a real anchor. Defensive throughout: a
// missing global, a missing next_steps, or a non-https href renders nothing
// rather than a broken card, because ChatGPT still shows the model's own text
// alongside - an empty widget costs a little space, a wrong one costs trust.
const WIDGET_HTML = `<!doctype html>
<meta charset="utf-8">
<style>
  :root { color-scheme: light dark; }
  .oa { font: 14px/1.45 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
        border: 1px solid rgba(128,128,128,.28); border-radius: 12px; padding: 14px 16px; }
  .oa h3 { margin: 0 0 6px; font-size: 14px; font-weight: 600; }
  .oa p { margin: 0 0 12px; opacity: .75; }
  .oa a.cta { display: inline-block; text-decoration: none; font-weight: 600;
              border: 1px solid currentColor; border-radius: 8px; padding: 8px 14px; }
  .oa ul { margin: 12px 0 0; padding-left: 18px; opacity: .75; }
  .oa li { margin: 2px 0; }
</style>
<div class="oa" id="oa" hidden>
  <h3 id="oa-title">Open this scenario on OptionsAhoy</h3>
  <p id="oa-sub">The free calculator, pre-filled with the numbers from this calculation - adjust anything and see it update.</p>
  <a class="cta" id="oa-cta" target="_blank" rel="noopener">Open pre-filled calculator</a>
  <ul id="oa-more"></ul>
</div>
<script>
(function () {
  function render() {
    try {
      var out = (window.openai && window.openai.toolOutput) || null;
      var next = out && out.next_steps;
      if (!next) return;
      var href = typeof next.web_tool === 'string' ? next.web_tool : '';
      // The line may be prose ending in the URL; take the URL itself.
      var at = href.indexOf('https://');
      href = at >= 0 ? href.slice(at) : '';
      if (!/^https:\\/\\/optionsahoy\\.com\\//.test(href)) return;
      var cta = document.getElementById('oa-cta');
      cta.setAttribute('href', href);
      if (href.indexOf('&mcp=') === -1) {
        document.getElementById('oa-sub').textContent =
          'Open the free calculator to work this through interactively.';
        cta.textContent = 'Open calculator';
      }
      if (typeof next.also_run === 'string' && next.also_run) {
        var li = document.createElement('li');
        li.textContent = next.also_run;
        document.getElementById('oa-more').appendChild(li);
      }
      document.getElementById('oa').hidden = false;
    } catch (e) { /* never break the host's rendering */ }
  }
  render();
  window.addEventListener('openai:set_globals', render);
})();
</script>`;

export const SCENARIO_WIDGET_RESOURCE = {
  uri: SCENARIO_WIDGET_URI,
  name: 'OptionsAhoy scenario link (ChatGPT widget)',
  description:
    'UI template referenced by the tools’ openai/outputTemplate metadata. Not a document: ChatGPT renders it to show the pre-filled calculator link verbatim. Other clients can ignore it.',
  mimeType: 'text/html+skybridge' as const,
  contents: WIDGET_HTML,
};
