// AlphaLatitude Inc. © 2026
//
// ChatGPT Apps SDK widget: the one path where our scenario link reaches the
// user VERBATIM.
//
// Why this exists. `content` and `structuredContent` are, per OpenAI's own
// reference, "surfaced to the model" - the assistant composes its reply FROM
// them, so a 400-char base64 scenario payload is regenerated by a language
// model and routinely mangled. Six observed ChatGPT runs of one question gave
// five different link treatments (omitted twice, whole once, src-only, twice
// stripped to the bare path). No instruction fixes that channel; it is lossy
// by construction.
//
// A widget is rendered by the CLIENT, not written by the model. An <a href>
// here arrives exactly as sent.
//
// ADDITIVE BY DESIGN. `content[0]` is still the JSON result and `content[1]`
// still the prose block carrying the same full URL, so the MODEL-VISIBLE
// surface is unchanged and clients that do not implement
// `_meta["openai/outputTemplate"]` (Claude, Cursor, npx/stdio, registries,
// plain SDK callers) behave exactly as before. What did change since the
// first cut, and is asserted in tests/chatgpt-widget.test.ts: tools/list and
// tool results carry `_meta`, resources/list carries the template, and every
// response carries `cache-control`. Unknown `_meta` is ignored per MCP spec.

/** Widget template URI, referenced from each tool's `_meta`. */
export const SCENARIO_WIDGET_URI = 'ui://widget/optionsahoy-scenario.html';

/** Tool-DESCRIPTOR `_meta`: template pointer plus the invocation status
 *  labels, which are descriptor-level by definition. */
export const SCENARIO_WIDGET_META = {
  'openai/outputTemplate': SCENARIO_WIDGET_URI,
  'openai/toolInvocation/invoking': 'Running the numbers',
  'openai/toolInvocation/invoked': 'Calculation complete',
} as const;

/** Tool-RESULT `_meta`: the pointer only. The invoking/invoked labels are
 *  descriptor-level status text with no defined meaning on a result, and
 *  every client receives this on every successful call. */
export const SCENARIO_WIDGET_RESULT_META = {
  'openai/outputTemplate': SCENARIO_WIDGET_URI,
} as const;

// Self-contained: no external scripts, styles, fonts or images, so no
// `_meta.ui.csp` declaration is needed and the sandbox cannot block us.
//
// The component reads `window.openai.toolOutput` (our structuredContent) and
// renders next_steps.web_tool as a real anchor. Defensive throughout: a
// missing global, a missing next_steps, or a non-https href renders nothing
// rather than a broken card, because ChatGPT still shows the model's own text
// alongside - an empty widget costs a little space, a wrong one costs trust.
const WIDGET_HTML = `<!doctype html>
<meta charset="utf-8">
<style>
  :root { color-scheme: light dark; }
  .oa { font: 14px/1.45 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
        border: 1px solid rgba(128,128,128,.28); border-radius: 12px; padding: 14px 16px; }
  .oa h3 { margin: 0 0 6px; font-size: 14px; font-weight: 600; }
  .oa p { margin: 0 0 12px; opacity: .75; }
  .oa a.cta { display: inline-block; text-decoration: none; font-weight: 600;
              border: 1px solid currentColor; border-radius: 8px; padding: 8px 14px; }
  .oa .url { margin: 10px 0 0; font-size: 11px; opacity: .5; word-break: break-all; }
</style>
<div class="oa" id="oa" hidden>
  <h3 id="oa-title">Open this scenario on OptionsAhoy</h3>
  <p id="oa-sub">The free calculator, pre-filled with the numbers from this calculation - adjust anything and see it update.</p>
  <a class="cta" id="oa-cta" target="_blank" rel="noopener noreferrer">Open pre-filled calculator</a>
  <p class="url" id="oa-url"></p>
</div>
<script>
(function () {
  // Only our own origin, host-case-insensitive per URL semantics, apex or www.
  // Anchored so the authority cannot be extended (optionsahoy.com.evil.com,
  // optionsahoy.com@evil.com both fail) and the href is guaranteed to start
  // with https:// before it is tested, so javascript:/data: are unreachable.
  var ORIGIN = /^https:\\/\\/(www\\.)?optionsahoy\\.com\\//i;

  // The host re-fires openai:set_globals at an effectively unbounded rate
  // ("more than 12" times for one answer, observed 2026-08-10), so this must
  // be both idempotent and cheap. Two protections: every write sets a
  // property (nothing accumulates - the first cut appended and stacked up),
  // and lastHref short-circuits identical re-renders.
  //
  // lastHref is committed only AFTER the card is shown. Committing it before
  // the writes meant one mid-render throw pinned a stale card VISIBLE
  // forever, advertising the previous tool's link while the reply described
  // the new one - a confidently wrong link, worse than no link at all.
  var lastHref = null;

  function render() {
    var card = document.getElementById('oa');
    try {
      var out = (window.openai && window.openai.toolOutput) || null;
      var next = out && out.next_steps;
      if (!next) { lastHref = null; card.hidden = true; return; }

      var raw = typeof next.web_tool === 'string' ? next.web_tool : '';
      var at = raw.indexOf('https://');
      var href = at >= 0 ? raw.slice(at) : '';
      if (!ORIGIN.test(href)) { lastHref = null; card.hidden = true; return; }
      if (href === lastHref) return;

      var prefilled = href.indexOf('&mcp=') !== -1;
      document.getElementById('oa-title').textContent = prefilled
        ? 'Open this scenario on OptionsAhoy'
        : 'Open this calculator on OptionsAhoy';
      document.getElementById('oa-sub').textContent = prefilled
        ? 'The free calculator, pre-filled with the numbers from this calculation - adjust anything and see it update.'
        : 'The free interactive calculator for this question.';
      var cta = document.getElementById('oa-cta');
      cta.setAttribute('href', href);
      cta.textContent = prefilled ? 'Open pre-filled calculator' : 'Open calculator';
      // Visible URL text: if the sandbox ever withholds allow-popups the
      // button is inert with no symptom, and this is the only way the link
      // survives that. Truncated because the payload is ~400 chars.
      document.getElementById('oa-url').textContent =
        href.length > 96 ? href.slice(0, 96) + '\\u2026' : href;

      card.hidden = false;
      lastHref = href;
    } catch (e) {
      // A partial render must not be left on screen, and must not be pinned.
      lastHref = null;
      try { card.hidden = true; } catch (e2) { /* nothing further we can do */ }
    }
  }
  render();
  window.addEventListener('openai:set_globals', render);
})();
</script>`;

export const SCENARIO_WIDGET_RESOURCE = {
  uri: SCENARIO_WIDGET_URI,
  name: 'OptionsAhoy scenario link (ChatGPT widget)',
  description:
    'UI template referenced by the tools’ openai/outputTemplate metadata. Not a document: ChatGPT renders it to show the pre-filled calculator link verbatim. Other clients can ignore it.',
  mimeType: 'text/html+skybridge' as const,
  contents: WIDGET_HTML,
};
